import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import combineComponents from '@/utils/combineComponents'
import ReactQueryProviders from '@/utils/react-query/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: React.PropsWithChildren) {
  const AppContextProviders = combineComponents([[ReactQueryProviders]])

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProviders>{children}</AppContextProviders>
      </body>
    </html>
  )
}
